<img src="Pipeline1.jpg" style="width:100"  alt="TEnsorflow Data Input Pipeline" title="Data Input Pipeline" />

                                       **Data Input Pipeline**
***

**In any Modeling Pipeline there are basaic generic steps to be followed.<br>
1: Get the data.<br>
2: EDA<br>
3: Preprocessing and Feature engineering<br>
4: Input the preprocessed and clean data to Modeling mechanism.<br>
5: Analyse the training output.<br>**

***

**To get started we need to get the dataset from any data source.<br>
Datasources can be located at:<br>
    1:in-memeory<br>
    2:Locally stored<br>
    3:Remotely deployed.<br>**
    
***    

**Data can have varying formats as well irrelavant of it's storage location:<br>
1: *Structured*  
2: *Unstructured*  
3: *Semi-Structured***

***

Based on the size of the data we start preprocessing and model training and testing on a specific architecture
For example if we have data with certain format and big size, we need to access it and utilize it with help of distributed manner.<br><br>
Based on the underlying hardware capabilities we can take advantage of underlying processing power for faster processing.<br>For an example we can run computation on **GPUs** or **TPUs** instead of assigning the processing to **CPUs**

&#129409;

***

In [1]:
from __future__ import absolute_import, division, print_function, unicode_literals

import pathlib
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import tensorflow as tf
np.set_printoptions(precision=4)

**Ways to create _Tensorflow Dataset_**

In [2]:
#Using from_tensor_slices(tensor)
dataset = tf.data.Dataset.from_tensor_slices([8, 3, 0, 8, 2, 1])

In [3]:
#Using from_tensors
dataset = tf.data.Dataset.from_tensors([1.2,3.4,5.6,7.8])

In [4]:
#Using from_generator
def gen():
    for i in itertools.count(1):
        yield (i, [1] * i)

dataset = tf.data.Dataset.from_generator(gen, (tf.int64, tf.int64), (tf.TensorShape([]), tf.TensorShape([None])))

In [5]:
#using tf.data.Dataset.zip((datasets seperated by comma))
dataset_1 = tf.data.Dataset.from_tensors([1,2,3])
dataset_2 = tf.data.Dataset.from_tensors([4,9,2])

dataset_3 = tf.data.Dataset.zip((dataset_1,dataset_2))

In [6]:
#Using experimental API
csv_file_path = "/home/sachin/Documents/BigData.csv"
dataset = tf.data.experimental.make_csv_dataset(
      csv_file_path,
      batch_size=5, # Artificially small to make examples easier to show.
      label_name="LABEL",
      na_value="?",
      num_epochs=1,
      ignore_errors=True)

Instructions for updating:
Use `tf.data.Dataset.interleave(map_func, cycle_length, block_length, num_parallel_calls=tf.data.experimental.AUTOTUNE)` instead. If sloppy execution is desired, use `tf.data.Options.experimental_determinstic`.


In [7]:
#Using TFRecordDataset
fsns_test_file = tf.keras.utils.get_file("fsns.tfrec", "https://storage.googleapis.com/download.tensorflow.org/data/fsns-20160927/testdata/fsns-00000-of-00001")
dataset = tf.data.TFRecordDataset(filenames=[fsns_test_file])

**<font color=green>Ways to iterate over the Tensorflow Dataset into Batches</font>**

In [28]:
dataset_1 = tf.data.Dataset.range(502)
batch_dataset = dataset_1.batch(20)

i=1
for batch in batch_dataset:
    print("\n\nBatch number :: ",i)
    i+=1    
    print(batch.numpy())



Batch number ::  1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


Batch number ::  2
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]


Batch number ::  3
[40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]


Batch number ::  4
[60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]


Batch number ::  5
[80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


Batch number ::  6
[100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
 118 119]


Batch number ::  7
[120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139]


Batch number ::  8
[140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157
 158 159]


Batch number ::  9
[160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177
 178 179]


Batch number ::  10
[180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199]


Batch number ::  11
[200 201 202 203 204 205 206 207 208 209 2

**Applying custom function to Tensorflow dataset**

In [ ]:
dataset = tf.data.Dataset.from_tensors(tf.random.uniform((1000)))

for 

